version: '3.8'

services:
  app:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn --host 0.0.0.0 acars_server.app:app'
    volumes:
      - .:/app
    ports:
      - 8000:8000
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=acars
      - POSTGRES_PASSWORD=acars
      - POSTGRES_DB=acars

volumes:
    postgres_data:
